BASE_DOMAIN_URL = "https://www.saucedemo.com/"
INVENTORY_ITEM = '//*[@class="inventory_item"]'
USERNAME = "*[data-test=\"username\"]"
PASSWORD = "*[data-test=\"password\"]"
LOGINBTN = "*[data-test=\"login-button\"]"
INVENTORY_ITEMNAME = "#item_4_title_link > .inventory_item_name"
ERROR = "*[data-test=\"error\"]"
DATA_TEST_ADD = "*[data-test=\"add-to-cart-sauce-labs-backpack\"]"
DATA_TEST_REMOVE = "*[data-test=\"remove-sauce-labs-backpack\"]"
BASKET = ".shopping_cart_badge"